// Angular/adminpro/src/app/auth/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { Usuario } from '../../shared/interfaces/usuario';
import { UsuariosService } from '../../usuarios.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  name:string = "";
  email:string = "";
  password:string = "";
  confirmPassword:string = "";
  constructor(private usuariosService:UsuariosService, private router:Router) { }

  ngOnInit(): void {
  }

  agregarUsuario() {
    if(this.name == "" || this.email == "" || this.password == "" || this.confirmPassword == "")
      return alert("Faltan campos por llenar para agregar el usuario.");
    if( this.password != this.confirmPassword)
      return alert("La contraseña no coincide, intente de nuevo.");
    let usuario:Usuario = {
      name : this.name,
      email : this.email,
      password : this.password
    };
    this.usuariosService.agregarUsuario(usuario).subscribe(usuario => {
      console.log(usuario);
      alert('Usuario registrado con exito.');
      this.router.navigate(['login']);
    });
    this.name = "";
    this.email = "";
    this.password = "";
    this.confirmPassword = "";
  }

}

<section id="wrapper" class="login-register login-sidebar" style="background-image:url(../assets/images/background/login-register.jpg);">
  <div class="login-box card">
      <div class="card-body">
          <form class="form-horizontal form-material" id="loginform" action="index.html">
              <a href="javascript:void(0)" class="text-center db"><img src="../assets/images/logo-icon.png" alt="Home" /><br/><img src="../assets/images/logo-text.png" alt="Home" /></a>
              <h3 class="box-title m-t-40 m-b-0">Register Now</h3><small>Create your account and enjoy</small>
              <div class="form-group m-t-20">
                  <div class="col-xs-12">
                      <input class="form-control" type="text" required="" placeholder="Name" name="txtName" [(ngModel)]="name">
                  </div>
              </div>
              <div class="form-group ">
                  <div class="col-xs-12">
                      <input class="form-control" type="text" required="" placeholder="Email"  name="txtEmail" [(ngModel)]="email">
                  </div>
              </div>
              <div class="form-group ">
                  <div class="col-xs-12">
                      <input class="form-control" type="password" required="" placeholder="Password" name="txtPassword" [(ngModel)]="password">
                  </div>
              </div>
              <div class="form-group">
                  <div class="col-xs-12">
                      <input class="form-control" type="password" required="" placeholder="Confirm Password" name="txtConfirmPassword" [(ngModel)]="confirmPassword">
                  </div>
              </div>
              <div class="form-group row">
                  <div class="col-md-12">
                      <div class="checkbox checkbox-primary p-t-0">
                          <input id="checkbox-signup" type="checkbox">
                          <label for="checkbox-signup"> I agree to all <a href="#">Terms</a></label>
                      </div>
                  </div>
              </div>
              <div class="form-group text-center m-t-20">
                  <div class="col-xs-12">
                      <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="button" (click)="agregarUsuario()">Sign Up</button>
                  </div>
              </div>
              <div class="form-group m-b-0">
                  <div class="col-sm-12 text-center">
                      <p>Already have an account? <a href="login" class="text-info m-l-5"><b>Sign In</b></a></p>
                  </div>
              </div>
          </form>
      </div>
  </div>
</section>

// Vue/dashboardvue/src/components/auth/RegisterComponent.vue
<template>
    <section id="wrapper" class="login-register login-sidebar" style="background-image:url(../assets/images/background/login-register.jpg);">
        <div class="login-box card">
            <div class="card-body">
                <form class="form-horizontal form-material" id="loginform" action="index.html">
                    <a href="javascript:void(0)" class="text-center db"><img src="../../assets/images/logo-icon.png" alt="Home" /><br/><img src="../../assets/images/logo-text.png" alt="Home" /></a>
                    <h3 class="box-title m-t-40 m-b-0">Register Now</h3><small>Create your account and enjoy</small>
                    <div class="form-group m-t-20">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Name" name="txtName" >
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Email"  name="txtEmail" >
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" required="" placeholder="Password" name="txtPassword" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" required="" placeholder="Confirm Password" name="txtConfirmPassword">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="checkbox checkbox-primary p-t-0">
                                <input id="checkbox-signup" type="checkbox">
                                <label for="checkbox-signup"> I agree to all <a href="#">Terms</a></label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="button" >Sign Up</button>
                        </div>
                    </div>
                    <div class="form-group m-b-0">
                        <div class="col-sm-12 text-center">
                            <p>Already have an account? <a href="login" class="text-info m-l-5"><b>Sign In</b></a></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
</template>

<style scoped>
    .login-register {
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
        height: 100%;
        width: 100%;
        padding: 10% 0;
        position: fixed; 
    }

    .login-box {
        width: 400px;
        margin: 0 auto; 
    }
    .login-box .footer {
        width: 100%;
        left: 0px;
        right: 0px; 
    }
    .login-box .social {
        display: block;
        margin-bottom: 30px; 
    }

    #recoverform {
        display: none; 
    }

    .login-sidebar {
        padding: 0px;
        margin-top: 0px; 
    }
    .login-sidebar .login-box {
        right: 0px;
        position: absolute;
        height: 100%; 
    }

</style>
