// Vue/dashboardvue/src/components/auth/LoginComponent.vue
<template>
    <section id="wrapper" class="login-register login-sidebar" style="background-image:url(../assets/images/background/login-register.jpg);">
        <div class="login-box card">
            <div class="card-body">
                <form class="form-horizontal form-material" id="loginform" action="index.html">
                    <a href="javascript:void(0)" class="text-center db"><img src="../../assets/images/logo-icon.png" alt="Home" /><br/><img src="../../assets/images/logo-text.png" alt="Home" /></a>
                    <div class="form-group m-t-40">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Username" name="txtEmail">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" required="" placeholder="Password" name="txtPassword" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12">
                            <div class="checkbox checkbox-primary pull-left p-t-0">
                                <input id="checkbox-signup" type="checkbox" class="filled-in chk-col-light-blue">
                                <label for="checkbox-signup"> Remember me </label>
                            </div>
                            <a href="javascript:void(0)" id="to-recover" class="text-dark pull-right"><i class="fa fa-lock m-r-5"></i> Forgot pwd?</a> </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-info btn-lg btn-block text-uppercase btn-rounded" type="button" >Log In</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-12 m-t-10 text-center">
                            <div class="social"><a href="javascript:void(0)" class="btn  btn-facebook" data-toggle="tooltip" title="Login with Facebook"> <i aria-hidden="true" class="fa fa-facebook"></i> </a> <a href="javascript:void(0)" class="btn btn-googleplus" data-toggle="tooltip" title="Login with Google"> <i aria-hidden="true" class="fa fa-google-plus"></i> </a> </div>
                        </div>
                    </div>
                    <div class="form-group m-b-0">
                        <div class="col-sm-12 text-center">
                            Don't have an account? <a href="register" class="text-primary m-l-5"><b>Sign Up</b></a>
                        </div>
                    </div>
                </form>
                <form class="form-horizontal" id="recoverform" action="index.html">
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <h3>Recover Password</h3>
                            <p class="text-muted">Enter your Email and instructions will be sent to you! </p>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-primary btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>

</template>

<style scoped>
.login-register {
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center center;
  height: 100%;
  width: 100%;
  padding: 10% 0;
  position: fixed; }

.login-box {
  width: 400px;
  margin: 0 auto; }
  .login-box .footer {
    width: 100%;
    left: 0px;
    right: 0px; }
  .login-box .social {
    display: block;
    margin-bottom: 30px; }

#recoverform {
  display: none; }

.login-sidebar {
  padding: 0px;
  margin-top: 0px; }
  .login-sidebar .login-box {
    right: 0px;
    position: absolute;
    height: 100%; 
    }

</style>

// Angular/adminpro/src/app/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { UsuariosService } from '../../usuarios.service';
import { Usuario } from '../../shared/interfaces/usuario';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  email:string = "";
  password:string = "";
  constructor(private usuariosService:UsuariosService, private router:Router) { }

  ngOnInit(): void {
  }

  verificarUsuario() {
    if(this.email == "" || this.password == "")
      return alert("Faltan campos por llenar");
    let usuario:Usuario = {
      name: "",
      email:this.email,
      password: this.password
    };
    this.usuariosService.getUsuario(usuario).subscribe(data => {
      console.log(data);
      if(data != false){
        this.email = "";
        this.password = "";
        this.router.navigate(['/dashboard']);
      }
      else{
        return alert('Las credenciales son incorrectas.');
      }
    });

  }
}

<section id="wrapper" class="login-register login-sidebar" style="background-image:url(../assets/images/background/login-register.jpg);">
  <div class="login-box card">
      <div class="card-body">
          <form class="form-horizontal form-material" id="loginform" action="index.html">
              <a href="javascript:void(0)" class="text-center db"><img src="../assets/images/logo-icon.png" alt="Home" /><br/><img src="../assets/images/logo-text.png" alt="Home" /></a>
              <div class="form-group m-t-40">
                  <div class="col-xs-12">
                      <input class="form-control" type="text" required="" placeholder="Username" name="txtEmail" [(ngModel)]="email">
                  </div>
              </div>
              <div class="form-group">
                  <div class="col-xs-12">
                      <input class="form-control" type="password" required="" placeholder="Password" name="txtPassword" [(ngModel)]="password">
                  </div>
              </div>
              <div class="form-group row">
                  <div class="col-md-12">
                      <div class="checkbox checkbox-primary pull-left p-t-0">
                          <input id="checkbox-signup" type="checkbox" class="filled-in chk-col-light-blue">
                          <label for="checkbox-signup"> Remember me </label>
                      </div>
                      <a href="javascript:void(0)" id="to-recover" class="text-dark pull-right"><i class="fa fa-lock m-r-5"></i> Forgot pwd?</a> </div>
              </div>
              <div class="form-group text-center m-t-20">
                  <div class="col-xs-12">
                      <button class="btn btn-info btn-lg btn-block text-uppercase btn-rounded" type="button" (click)="verificarUsuario()">Log In</button>
                  </div>
              </div>
              <div class="row">
                  <div class="col-xs-12 col-sm-12 col-md-12 m-t-10 text-center">
                      <div class="social"><a href="javascript:void(0)" class="btn  btn-facebook" data-toggle="tooltip" title="Login with Facebook"> <i aria-hidden="true" class="fa fa-facebook"></i> </a> <a href="javascript:void(0)" class="btn btn-googleplus" data-toggle="tooltip" title="Login with Google"> <i aria-hidden="true" class="fa fa-google-plus"></i> </a> </div>
                  </div>
              </div>
              <div class="form-group m-b-0">
                  <div class="col-sm-12 text-center">
                      Don't have an account? <a href="register" class="text-primary m-l-5"><b>Sign Up</b></a>
                  </div>
              </div>
          </form>
          <form class="form-horizontal" id="recoverform" action="index.html">
              <div class="form-group ">
                  <div class="col-xs-12">
                      <h3>Recover Password</h3>
                      <p class="text-muted">Enter your Email and instructions will be sent to you! </p>
                  </div>
              </div>
              <div class="form-group ">
                  <div class="col-xs-12">
                      <input class="form-control" type="text" required="" placeholder="Email">
                  </div>
              </div>
              <div class="form-group text-center m-t-20">
                  <div class="col-xs-12">
                      <button class="btn btn-primary btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Reset</button>
                  </div>
              </div>
          </form>
      </div>
  </div>
</section>
